"""
3_🛠️_Create_Playlists.py – Classifica AI e Crea Playlist su Spotify
"""
import streamlit as st
import pandas as pd
import json
import os
from spotify_client import (
    get_or_create_playlist,
    add_tracks_to_playlist,
    get_auth_manager,
    get_spotify_client,
)
from gemini_classifier import classify_all_tracks
from classifier import (
    build_year_buckets,
    build_genre_buckets,
    YEAR_PLAYLISTS,
    GENRE_PLAYLISTS,
)
from spotipy.exceptions import SpotifyException

st.set_page_config(page_title="Create Playlists", page_icon="🛠️", layout="wide")

if "sp" not in st.session_state:
    st.warning("⚠️ Non sei autenticato. Torna alla Home page per fare il login.")
    st.stop()
    
sp = st.session_state["sp"]
user_id = st.session_state["user"]["id"]
tracks = st.session_state.get("tracks", [])

if not tracks:
    st.warning("⚠️ Nessuna traccia da processare. Torna alla Home.")
    st.stop()


# ── LOGIC FUNCTIONS (COPIED FROM APP.PY) ──

def _save_created_history(new_entries):
    """Salva storico su file."""
    try:
        hist_file = f"user_data/history_{user_id}.json"
        existing = []
        if os.path.exists(hist_file):
            with open(hist_file, "r", encoding="utf-8") as f:
                existing = json.load(f)
        
        existing_map = {item["Playlist"]: item for item in existing}
        for entry in new_entries:
            existing_map[entry["Playlist"]] = entry
        
        final_list = list(existing_map.values())
        with open(hist_file, "w", encoding="utf-8") as f:
            json.dump(final_list, f, indent=2)
    except Exception as e:
        print(f"Error saving history: {e}")

def create_playlists_action(mode="all"):
    """Esegue la creazione effettiva su Spotify."""
    year_buckets = st.session_state.get("year_buckets", {})
    genre_buckets = st.session_state.get("genre_buckets", {})
    
    all_buckets = {}
    if mode in ["all", "decades"]:
        all_buckets.update(year_buckets)
    if mode in ["all", "genres"]:
        all_buckets.update(genre_buckets)
        
    if not all_buckets:
        st.warning("Nessuna categoria pronta per la creazione.")
        return

    st.subheader(f"🚀 Creazione in corso ({mode})...")
    progress_bar = st.progress(0, text="Avvio...")
    total = len(all_buckets)
    
    auth_manager = get_auth_manager() # Refresh auth/scopes check
    
    created_now = []

    try:
        for idx, (name, bucket) in enumerate(all_buckets.items(), 1):
            if not bucket: continue
            
            progress_bar.progress(idx / total, text=f"Creating: {name}...")
            
            # Crea Playlist
            pid = get_or_create_playlist(
                sp, user_id, name, 
                description=f"Auto-generated by AlgoRhythm 🎵 ({len(bucket)} tracks)"
            )
            
            # Aggiungi Tracce
            uris = [t["track_id"] for t in bucket]
            add_tracks_to_playlist(sp, pid, uris)
            
            created_now.append({"Playlist": name, "Brani": len(bucket)})
            st.session_state["created_info"] = st.session_state.get("created_info", []) + created_now
            
    except SpotifyException as e:
        if e.http_status == 403:
            st.error("🚨 ERRORE PERMESSI (403).")
            st.error("Il tuo token non ha i permessi per creare playlist o l'utente non è autorizzato.")
            if st.button("Logout Forzato"):
                st.session_state.clear()
                st.rerun()
        else:
            st.error(f"Errore Spotify: {e}")
            raise e
            
    progress_bar.progress(1.0, text="Fatto!")
    _save_created_history(created_now)
    st.success(f"✅ Create {len(created_now)} playlist!")
    st.balloons()


# ── UI ──

st.title("🛠️ Laboratorio Playlist")

tab1, tab2 = st.tabs(["1. Classificazione AI", "2. Creazione Su Spotify"])

# TAB 1: CLASSIFICAZIONE
with tab1:
    st.markdown("### 🤖 Analisi AI dei Generi")
    st.write("Usa Gemini per analizzare il mood di ogni brano.")
    
    if st.button("▶️ Avvia Analisi AI"):
        st.info("Avvio processo classificazione...")
        
        container = st.container()
        progress = st.progress(0)
        
        # Generator
        gen = classify_all_tracks(tracks)
        current_class = st.session_state.get("classifications", {})

        try:
            for b_num, total_b, b_res in gen:
                pct = b_num / total_b if total_b else 0
                progress.progress(pct, text=f"Batch {b_num}/{total_b}")
                
                # Update partial results
                current_class.update(b_res)
                st.session_state["classifications"] = current_class
                
                # Show sample
                with container:
                    # Show last 3 classified
                    items = list(b_res.items())[-3:]
                    txt = " | ".join([f"{k}: {v}" for k,v in items])
                    st.caption(f"Last batch: {txt}")

        except Exception as e:
            st.error(f"Errore AI: {e}")
            
        st.success("Analisi completata!")
        
        # Build buckets immediately
        st.session_state["genre_buckets"] = build_genre_buckets(tracks, current_class)


# TAB 2: CREAZIONE
with tab2:
    st.markdown("### 🚀 Genera Playlist")
    
    # Check if we have data
    year_buckets = st.session_state.get("year_buckets", {})
    if not year_buckets:
        st.session_state["year_buckets"] = build_year_buckets(tracks)
        year_buckets = st.session_state["year_buckets"]
        
    genre_buckets = st.session_state.get("genre_buckets", {})
    
    col_a, col_b = st.columns(2)
    
    with col_a:
        st.info("📅 **Playlist Decadi** (Anni '90, '00...)")
        st.write(f"Pronte: **{len(year_buckets)}** playlist temporali.")
        if st.button("Crea Playlist Decadi", key="btn_decades"):
            create_playlists_action("decades")

    with col_b:
        st.info("🎭 **Playlist Generi AI** (Mood, Vibe...)")
        if genre_buckets:
            st.write(f"Pronte: **{len(genre_buckets)}** playlist per genere.")
            if st.button("Crea Playlist Generi AI", key="btn_genres"):
                create_playlists_action("genres")
        else:
            st.warning("⚠️ Esegui prima l'analisi AI nel Tab 1!")

    st.markdown("---")
    st.write("### 📜 Storico Creazioni")
    
    hist = st.session_state.get("created_info", [])
    if not hist:
        # Load from file if empty
        try:
             hist_file = f"user_data/history_{user_id}.json"
             if os.path.exists(hist_file):
                 with open(hist_file) as f:
                     hist = json.load(f)
                     st.session_state["created_info"] = hist
        except: pass

    if hist:
        st.dataframe(pd.DataFrame(hist))
    else:
        st.caption("Nessuna playlist creata finora.")
